# Generated by Django 6.0.3 on 2026-05-02 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0002_remove_event_room_emergency_delete_attends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
