# Generated by Django 6.0.3 on 2026-05-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('createevent', '0003_emergency_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_emergencies', to='account.account'),
        ),
    ]
