# Generated by Django 6.0.3 on 2026-03-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1)),
            ],
        ),
    ]
