# Generated by Django 6.0.3 on 2026-03-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventTitle', models.CharField(max_length=100)),
                ('dateOfEvent', models.DateField()),
                ('maxParticipants', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='createevent.room')),
            ],
        ),
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('dateRegistered', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createevent.event')),
            ],
            options={
                'unique_together': {('username', 'event')},
            },
        ),
    ]
